services:
  forgejo:
    environment:
      FORGEJO__server__DOMAIN: "${FORGEJO_PUBLIC_DOMAIN}"
      FORGEJO__server__ROOT_URL: "https://${FORGEJO_PUBLIC_DOMAIN}/"
      FORGEJO__server__SSH_DOMAIN: "${FORGEJO_PUBLIC_DOMAIN}"
